#!/bin/bash

# Identify and display the Ethernet interface characteristics:
# Identify broadcast address
# Identify all IP adresses which are part of the same subnet

#ifconfig en0 | grep "broadcast" | cut -d ' ' -f6
arp -a | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'