#!/bin/bash
#
# Write a script which delete an ACTIVE user on the VM.

ACTIVE=$(who | awk '{print $1}')
echo "Account you want to delete?"; read ACC
if  grep -q "$ACTIVE" <<< $ACC; then
	sudo pkill -9 -u $ACC
	sudo userdel -rf $ACC
	echo "User $ACC has been deleted!"
else
	printf "Account is not logged in or it does not exists!\n"
fi